### ISSUE TITLE
Investigate better protocols than 9p

### ISSUE THREAD

**Issue by rminnich** [Harvey-OS/harvey#18] opened 2015-08-20 03:51 UTC
9p is a dog. It has some fundamental design limits which seem to cause performance problems. One of them is the requirement that all operations on a connection be serialized. Another is that it's always one connection.The statefulness of 9p, which at one point seemed sensible, is now an anchor dragging along behind it. 

We need to investigate newer protocols to see if they are better. Now that we can select from multiple mount devices, we could mount those new protocols over a new mount device and see if performance improves.

We can also investigate improvements to 9p but, note, the problem is much, much harder than it first seems.

**Comment by witheld9** [comment] 2016-05-28 13:53
What the hell is wrong with you people

**Comment by mennis** [comment] 2016-08-08 21:13
rminnich,  Are your observations about the causes of 9p's performance issues elucidated elsewhere?

**Comment by rminnich** [comment] 2016-08-08 22:58
from slack:
important tools for latency tolerance are speculation (i.e. prefetch), batching (e.g. concatenating writes, postwrite) pipelining (multiple ops in flight), and 9p makes all of these impossible. The big problem is using the same protocol for hardware (e.g. mouse) and files. I think experience shows that does not work.

**Comment by kanarok** [comment] 2016-09-06 23:05
I've tried to find an older article, I've read some time ago, stating what went wrong in Plan9 and Inferno.
If I recall correctely the authentication is part of 9p which was one of the big mistakes. Just speaking for the cause of improvement

**Comment by rminnich** [comment] 2016-09-06 23:38
If you could find a source and excerpt it that would help, but I have never seen that the authentication is a big problem. Once the connection is set up, there is no per-packet authentication as in, e.g., NFS. So I'm not sure what you mean.

**Comment by kanarok** [comment] 2016-09-07 10:57
I'm trying to find it again but can make no promises.

As far is I recall the problem only occurs if you like to change the authentication itself, the transition will be painful. Also I remember that they were speaking of shared private key which would compromise the whole network.

**Comment by kanarok** [comment] 2016-09-07 11:26
Ok I put some extended effort in finding that paper.

What I have found so far:
https://swtch.com/~rsc/talks/nauth.pdf

is not the paper I related to but describes the problem as following:
"Auth protocol hard wired into 9P
fixing an auth bug would require redefining 9P"

But I do not know if this is still valid. (See title: Problems
with Plan 9 authentication (now fixed))

**Comment by 0intro** [comment] 2016-09-07 12:21
> But I do not know if this is still valid.

The issues you mention were fixed in the new authentication mechanism,
as part of the the Fourth Edition of Plan 9, released in 2002.

See the paper [Security in Plan 9](http://9p.io/sys/doc/auth.html).

**Comment by ILOVEPIE** [comment] 2017-02-27 01:14
I'm working on a protocol called mpbmfp which stands for multiplexing binary markup filesystem protocol which is an asynchronous filesystem protocol based around the Extensible Binary Markup Language. I'm designing it to resolve as many of the issues of 9P i can: 9P is synchronous, mpbmfp is async; 9P can only carry 1 stream at a time, mpbmfp multiplexes streams and can run using multiple connections between two hosts simultaneously; 9P is unencrypted, mpbmfp is both compressed and encrypted etc.

**Comment by sevki** [comment] 2017-02-27 09:31
@ILOVEPIE that sounds interesting, do you have any literature we can read?

**Comment by ILOVEPIE** [comment] 2017-02-28 08:54
@sevki the documentation for the EBML format is on the matroska video container website, it's what their video container is based on. Ill write up a full description when i commit the work i've started on for a FUSE driver that supports the protocol.

**Comment by rminnich** [comment] 2017-02-28 17:50
You do NOT need a fuse driver to test the protocol. You do protocol test with test environments.

**Comment by ILOVEPIE** [comment] 2018-01-25 18:27
Been kinda busy sorry about this, ill join you guys on slack at some point to give a formal explanation of how the protocol works.

**Comment by Clyybber** [comment] 2018-07-25 13:17
@ILOVEPIE @rminnich Any updates on this?

**Comment by gmacd** [comment] 2020-07-06 20:14
Spring cleaning - closing old issues

**Closed by gmacd** 2020-07-06 20:14 UTC
Labels: disscussion
